export const arrOfLangs = [
  {
    Arabic: "Zeina",
    "Australian English": "Russell",
    "Brazilian Portuguese": "Vitória",
    "British English": "Emma",
    "Canadian French": "Chantal",
    "Castilian Spanish": "Conchita",
    "Chinese Mandarin": "Zhiyu",
    Danish: "Naja",
    Dutch: "Ruben",
    French: "Céline",
    German: "Hans",
    Icelandic: "Dóra",
    "Indian English": "Aditi",
    Italian: "Bianca",
    Japanese: "Takumi",
    Kean: "Seoyeon",
    "Mexican Spanish": "Mia",
    Norwegian: "Liv",
    Polish: "Jacek",
    Portuguese: "Cristiano",
    Romanian: "Carmen",
    Russian: "Maxim",
    Swedish: "Astrid",
    Turkish: "Filiz",
    "US English": "Salli",
    "US Spanish": "Lupe",
    Welsh: "Gwyneth",
    "Welsh English": "Geraint",
  },
];
